### ISSUE TITLE
使用dart-sass构建失败

### ISSUE THREAD

**Issue by Bubbu0129** [Keldos-Li/typora-latex-theme#158]
### Info
Arch Linux
dart-sass 1.79.4

### Issue
根据贡献指南安装`dart-sass`后，运行`make`报错。
将[Makefile, lines 21-25](https://github.com/Keldos-Li/typora-latex-theme/blob/main/src/Makefile#L21-L25)中的`scss --sourcemap=none`改为`sass --no-source-map`可以解决此问题；前者似乎是`ruby-sass`的写法。
编译时，也存在多个Warning:
```
Deprecation Warning: As of Dart Sass 2.0.0, !global assignments won't be able to declare new variables.
Recommendation: add `$<variable>: null` at the stylesheet root.
```
似乎是`dart-sass`兼容问题。

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I've updated the Makefile to use the dart-sass syntax instead of the ruby-sass syntax. This should resolve the issue you were experiencing when running `make`. I've replaced `scss --sourcemap=none` with `sass --no-source-map` in the build function. This change should be compatible with dart-sass 1.79.4.

I also created pull request: https://github.com/Keldos-Li/typora-latex-theme/pull/159


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by RalXYZ** [comment]
@Bubbu0129 非常感谢您的反馈。
贡献文档中的内容与 CI/CD 的环境不对齐。在本项目的 CI/CD 环境中，我们采用的是 ruby sass。这是不好的。
https://github.com/Keldos-Li/typora-latex-theme/blob/6c02fbf674dad04ac21875d76a68854082b6b035/.github/workflows/dev-build.yml#L18
https://github.com/Keldos-Li/typora-latex-theme/blob/6c02fbf674dad04ac21875d76a68854082b6b035/.github/workflows/release.yml#L15

我觉得我们现在应该彻底解决这一问题，包括：
1. 确保项目的 CI/CD 使用 https://www.npmjs.com/package/sass ，即 dart sass。与 CI/CD 相关的配置文件，仅有上面引用的两个文件。
2. 基于 1，检查编译过程中出现的全部警告、错误，并全部予以解决。

如果您愿意完成以上两点工作内容，在工作完成后，相关的 pr 即可被合入主线。如果您无暇跟进，我们会基于您的工作完成上述两点工作内容，并给您合适的 credit ；随后相关的 pr 也会被合入主线。
无论如何，再次感谢您。

**Comment by Bubbu0129** [comment]
1. 项目的CI/CD通过安装 GitHub release asset tarball 的方式迁移到 dart sass。`dev-build` action在我的fork上测试成功。
2. 针对 dart sass，已经解决了本地编译的全部警告和问题。

PS: 我并不熟悉 GitHub Action，如有错误请多包涵。在改动workflow的时候，相比于配置 node.js 环境后再使用 npm 安装 Dart Sass，我认为直接从 [sass/dart-sass](https://github.com/sass/dart-sass) Release 中下载二进制文件更为直接。

**Comment by Bubbu0129** [comment]
已将 dart sass 版本固定到 1.79.6。#161 解决后，可以再将 dart sass 升级到 1.80。
希望您在 wiki 贡献指南中指明 dart sass 的版本；同时，我在调试的时候触发了多次 workflow，问题解决后您可以把失败的 workflow run 删除。

**Comment by RalXYZ** [comment]
> 同时，我在调试的时候触发了多次 workflow，问题解决后您可以把失败的 workflow run 删除。
感谢提醒，这个我觉得也不必删了

再次感谢您的贡献和配合
