### ISSUE TITLE
Linux support request

### ISSUE THREAD

**Issue by Achazwl** [Keldos-Li/typora-latex-theme#20]
I tried using all combination of mac/windows css + mac/win/general font, all have font problem that dosen't looks like your given template? What did I missed?

**Comment by RalXYZ** [comment]
Hi William.  
The truth is that on Linux, **Chinese characters may not be displayed in the expected font**. This is due to the fact that there are many Linux distributions and desktop environments, and we have not yet investigated the default Chinese fonts for the different desktop environments, nor have we tested whether our CSS can find the desired fonts as expected. Moreover, as you can see, we do not have a Linux directory in the root of our main branch yet, which implies that our project does not fully support Linux at the moment.  
If you are writing a report in English, you will currently get the expected results on Linux. Currently, we are working on Chinese character support on Linux, and you are welcome to contribute to this project if you wish.  

William 你好。  
事实是，在 Linux 上，**中文可能并不能采用符合预期的字体显示**。这是由于 Linux 的发行版及桌面环境有很多，我们暂时还没有调查不同桌面环境的中文默认字体，也没有测试我们的 CSS 能否符合预期地找到所需的字体。你可以看到，在我们 main 分支的根目录下，还暂时没有 Linux 的目录，这也侧面说明了目前我们的项目不完全支持 Linux。  
如果你撰写的是英文报告，那么目前你在 Linux 上是能得到符合预期的结果的。我们正在做对 Linux 的中文支持，如果你愿意，也欢迎向这个项目贡献代码。  

另外，我们的工作语言是中文或英文，所以接下来的交流，你可以选择用中文进行 :)

**Comment by Achazwl** [comment]
好哒谢谢，你们辛苦了 : )

**Comment by RalXYZ** [comment]
目前的方案是使用 `Noto Serif CJK` 
原因如下：
- 它是一个衬线字体
- 它是一个**热门**的字体
- 它是一个自由字体，且使用一种自由字体协议开源
条件如下：
- 该字体应当被放在列表的最后，作为 fallback
