### ISSUE TITLE
Fonts problem

### ISSUE THREAD

**Issue by Esayanubn** [Keldos-Li/typora-latex-theme#6]
when I try to install the fonts file in the `/Supplemental/Fonts` in Windows 10, these four files in attachment can't be installed and opened. Meanwhile, after I installed the files that could be install and changed the theme to "latex(typora-latex-theme)", it seems still no fonts showed.
![QN(2G59$G~DJH~$FF0EYGVK](https://user-images.githubusercontent.com/81795187/120094713-a97eb880-c154-11eb-84c1-9e350dba1a35.png)

**Comment by Keldos-Li** [comment]
我猜测是因为这几个字体文件是直接从苹果系统字体里导出来的，字体文件中额外放置了一些信息阻止它们被传播与二次安装。

*macOS用户理论上不需要重新安装这些字体*

如果有人能解决请告诉我。或许我应该重新找一些字体文件让非macOS用户安装。在下一个版本更新前，请您先替换电脑中的可用字体。不过我猜除了苹方其他的字体在Windows中也是默认安装的(吧)。

----

I guess it's because these font files are directly exported from the Apple system font, and some information is placed in the font file to prevent them from being spread and re-installed. 

*macOS users theoretically do not need to reinstall these fonts*

If someone can solve this, please tell me. Maybe I should re-find some font files for non-macOS users to install. Before the next version is updated, please replace them with the available fonts on your computer. But I guess other fonts besides `pingfang` are already installed by default in Windows.

**Comment by Keldos-Li** [comment]
另外大家提issue可以用中文。**都是中国大学生**。外国用户应该已经被我赶走了……🤔

**Comment by Keldos-Li** [comment]
有人试试用这个方法尝试下吗 https://appuals.com/fix-does-not-appear-to-be-a-valid-font/

**Comment by Keldos-Li** [comment]
win的字体渲染机制就是一坨屎

啊啊啊再见吧

在改了在改了。

我要不要用两个branch一个Mac一个Win啊

**Comment by Keldos-Li** [comment]
@Esayanubn 尽管我确实还没能解决font安装的问题，但是我确信我暂时修复了latex亮色主题字体没有显示效果和偏好设置中显示效果的问题。新的代码存放在命名为 "iss6" 的一个新 branch下 的 css 文件夹中，名字为`latex-win.css`，还未进行合并，如有需要可先下载测试！谢谢！

**Comment by Keldos-Li** [comment]
> @Esayanubn 尽管我确实还没能解决font安装的问题，但是我确信我暂时修复了latex亮色主题字体没有显示效果和偏好设置中显示效果的问题。新的代码存放在命名为 "iss6" 的一个新 branch下 的 css 文件夹中，名字为`latex-win.css`，还未进行合并，如有需要可先下载测试！谢谢！
> #7

**Comment by Keldos-Li** [comment]
好吧我错了

**Comment by Keldos-Li** [comment]
现在应该可以了。
